activemq:
  container_name: activemq
  image: rmohr/activemq:5.14.5-alpine
  ports:
    - 8161:8161
    - 61616:61616
    - 61613:61613
  volumes:
    - /container_data/activemq/data:/data/activemq
    - /container_data/activemq/log:/var/log/activemq
  environment:
    ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
    ACTIVEMQ_ADMIN_LOGIN: admin
    ACTIVEMQ_ADMIN_PASSWORD: nimda
#      ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
#      ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
#      ACTIVEMQ_ENABLED_SCHEDULER: "true"
#      ACTIVEMQ_MIN_MEMORY: 512
#      ACTIVEMQ_MAX_MEMORY: 2048