activemq:
  container_name: activemq
  image: rmohr/activemq:5.14.5-alpine
  ports:
    - 8161:8161
    - 61616:61616
    - 61613:61613
  volumes:
    - /container_data/activemq/data:/data/activemq
    - /container_data/activemq/log:/var/log/activemq
  environment:
    ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
    ACTIVEMQ_ADMIN_LOGIN: admin
    ACTIVEMQ_ADMIN_PASSWORD: nimda
mongodb:
  image: mongo:latest
  container_name: "mongodb"
  hostname: mongodb
  environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
  volumes:
    - ./data/db:/data/db
  ports:
    - 27017:27017
  command: mongod --smallfiles --logpath=/dev/null # --quiet